"""initial_schema

Revision ID: 4ad74a1f7b25
Revises: None
Create Date: 2026-09-25 20:57:40.648421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad74a1f7b25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mqtt_topic', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trackers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trackers_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'USER', name='roleenum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('tracker_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_min_temp', sa.Float(), nullable=False),
    sa.Column('allowed_max_temp', sa.Float(), nullable=False),
    sa.Column('grace_period_readings', sa.Integer(), nullable=False),
    sa.Column('breach_active', sa.Boolean(), nullable=False),
    sa.Column('breach_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allowed_min_temp < allowed_max_temp', name='chk_min_less_than_max_temp'),
    sa.CheckConstraint('grace_period_readings >= 1', name='chk_grace_period_readings_positive'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_tracker_id'), ['tracker_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('tracker_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_tracker_id'), ['tracker_id'], unique=False)

    op.create_table('telemetry_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('tracker_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('door_open', sa.Boolean(), nullable=False),
    sa.CheckConstraint('battery_level IS NULL OR (battery_level >= 0.0 AND battery_level <= 100.0)', name='chk_battery_bounds'),
    sa.CheckConstraint('humidity IS NULL OR (humidity >= 0.0 AND humidity <= 100.0)', name='chk_humidity_bounds'),
    sa.CheckConstraint('latitude >= -90.0 AND latitude <= 90.0', name='chk_latitude_bounds'),
    sa.CheckConstraint('longitude >= -180.0 AND longitude <= 180.0', name='chk_longitude_bounds'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_readings', schema=None) as batch_op:
        batch_op.create_index('idx_shipment_timestamp', ['shipment_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_readings_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_readings_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_readings_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_readings_tracker_id'), ['tracker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_readings_tracker_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_readings_timestamp'))
        batch_op.drop_index(batch_op.f('ix_telemetry_readings_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_readings_organization_id'))
        batch_op.drop_index('idx_shipment_timestamp')

    op.drop_table('telemetry_readings')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_tracker_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_organization_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_tracker_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_organization_id'))

    op.drop_table('shipments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('trackers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trackers_organization_id'))

    op.drop_table('trackers')
    op.drop_table('organizations')
    # ### end Alembic commands ###
