"""add_consecutive_breach_count

Revision ID: 78180112a252
Revises: '4ad74a1f7b25'
Create Date: 2026-09-26 11:27:53.810253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78180112a252'
down_revision: Union[str, None] = '4ad74a1f7b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutive_breach_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('consecutive_breach_count')

    # ### end Alembic commands ###
